### ISSUE TITLE
Having trouble making rows disappear on smaller screens

### ISSUE THREAD

**Issue by jdlam** [jdlam/RESTaurant#1]
So using Materialize, I've made my app responsive, so its layout changes when put onto a mobile device. I'm having issues with removing the `</div><div class="row">` on the smaller screen though. It's a minor detail on the app, but it does add a lot of space in between buttons. This is most notable when going through the list of foods when creating a new order.

http://localhost:9292/parties/orders/14/new?

You don't have the database there, but that's the page i'm specifically talking about

**Comment by emilylordahl** [comment]
I'm cloning your repo down now so I can take a look? Is this just a visual problem?

**Comment by jdlam** [comment]
Yeah. I want the `</div><div class="row">` to disappear when the screen is a smaller size. Functionality wise, my app is working fine so far.

**Comment by jdlam** [comment]
I didn't realize the code snippets disappear if I don't use the triple ` haha...

**Comment by emilylordahl** [comment]
Yeeeeeeeeeah! What's disappearing? I've not used Materialize so I'm not sure I'll be much help :smirk:

**Comment by jdlam** [comment]
Oh haha. So if you look in the views/orders/index.erb, on line 21, i'm using `</div><div class="row">` to end the row, and then create a new one. Along with a counter. This is great for the larger window sizes, but when I shrink the page down to a smaller size, like a width of 400px, then there's a larger gap between the panels where it starts a new row.

I'm just trying to get rid of that extra white space, so all of the panels are evenly spaced throughout

**Comment by emilylordahl** [comment]
_In person_
